development:
  LINKEDIN_APP_ID: mky987r927xk
  LINKEDIN_APP_SECRET: J6mdxQRCxLzFylVG
  TWITTER_CONSUMER_KEY: JCml0HxekzC5d3baAmWTew
  TWITTER_CONSUMER_SECRET: rOLlBBF4RbuIMKGF7DhyAieJZlYKmHAsihqam3hwi4s

test:
  LINKEDIN_APP_ID: mky987r927xk
  LINKEDIN_APP_SECRET: J6mdxQRCxLzFylVG
  TWITTER_CONSUMER_KEY: JCml0HxekzC5d3baAmWTew
  TWITTER_CONSUMER_SECRET: rOLlBBF4RbuIMKGF7DhyAieJZlYKmHAsihqam3hwi4s

production:
  LINKEDIN_APP_ID: 776lxo8io7pf
  LINKEDIN_APP_SECRET: 3yyNxefUTnVrMbUw
  TWITTER_CONSUMER_KEY: JCml0HxekzC5d3baAmWTew
  TWITTER_CONSUMER_SECRET: rOLlBBF4RbuIMKGF7DhyAieJZlYKmHAsihqam3hwi4s