development:
  LINKEDIN_APP_ID: mky987r927xk
  LINKEDIN_APP_SECRET: J6mdxQRCxLzFylVG
  TWITTER_CONSUMER_KEY: JCml0HxekzC5d3baAmWTew
  TWITTER_CONSUMER_SECRET: rOLlBBF4RbuIMKGF7DhyAieJZlYKmHAsihqam3hwi4s

test:
  LINKEDIN_APP_ID: mky987r927xk
  LINKEDIN_APP_SECRET: J6mdxQRCxLzFylVG
  TWITTER_CONSUMER_KEY: JCml0HxekzC5d3baAmWTew
  TWITTER_CONSUMER_SECRET: rOLlBBF4RbuIMKGF7DhyAieJZlYKmHAsihqam3hwi4s

production:
  LINKEDIN_APP_ID: nawbofkrvxyj
  LINKEDIN_APP_SECRET: ItE7nmh07Iv6H1qV
  TWITTER_CONSUMER_KEY: h39Fh1wjyBdh7OjQSbR6A
  TWITTER_CONSUMER_SECRET: w1xu87gQHmA4XJHaSUJmHYNOPiYPUTfozG6ljIM