development:
  linkedin_app_id: mky987r927xk
  linkedin_app_secret: J6mdxQRCxLzFylVG

test:
  linkedin_app_id: mky987r927xk
  linkedin_app_secret: J6mdxQRCxLzFylVG

production:
  linkedin_app_id: 776lxo8io7pf
  linkedin_app_secret: 3yyNxefUTnVrMbUw
  
staging:
  linkedin_app_id: 8bzlmanzd6l4
  linkedin_app_secret: 03XDpEwoMCSQKzmU