development:
  LINKEDIN_APP_ID: mky987r927xk
  LINKEDIN_APP_SECRET: J6mdxQRCxLzFylVG
  TWITTER_CONSUMER_KEY: JCml0HxekzC5d3baAmWTew
  TWITTER_CONSUMER_SECRET: rOLlBBF4RbuIMKGF7DhyAieJZlYKmHAsihqam3hwi4s

test:
  LINKEDIN_APP_ID: mky987r927xk
  LINKEDIN_APP_SECRET: J6mdxQRCxLzFylVG
  TWITTER_CONSUMER_KEY: JCml0HxekzC5d3baAmWTew
  TWITTER_CONSUMER_SECRET: rOLlBBF4RbuIMKGF7DhyAieJZlYKmHAsihqam3hwi4s

production:
  LINKEDIN_APP_ID: coveebf0c2rm
  LINKEDIN_APP_SECRET: 17hIMOSdfDtn9Nci
  TWITTER_CONSUMER_KEY: 0BsxZ6hmHdnX9oU5OnQ4A
  TWITTER_CONSUMER_SECRET: iZnj7UGhkG6Ul08GowO6Qh4DwkAhMAOAWP7OdRWJ7U